export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const GET_MY_PROFILE_REQUEST = "GET_MY_PROFILE_REQUEST";
export const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
export const GET_MY_PROFILE_FAILURE = "GET_MY_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const ASK_QUESTION_REQUEST = "ASK_QUESTION_REQUEST";
export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";
export const ASK_QUESTION_FAILURE = "ASK_QUESTION_FAILURE";

export const FETCH_ALL_QUESTIONS_REQUEST = "FETCH_ALL_QUESTIONS_REQUEST";
export const FETCH_ALL_QUESTIONS_SUCCESS = "FETCH_ALL_QUESTIONS_SUCCESS";
export const FETCH_ALL_QUESTIONS_FAILURE = "FETCH_ALL_QUESTIONS_FAILURE";

export const FETCH_SINGLE_QUESTION_REQUEST = "FETCH_SINGLE_QUESTION_REQUEST";
export const FETCH_SINGLE_QUESTION_SUCCESS = "FETCH_SINGLE_QUESTION_SUCCESS";
export const FETCH_SINGLE_QUESTION_FAILURE = "FETCH_SINGLE_QUESTION_FAILURE";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILURE = "DELETE_QUESTION_FAILURE";

export const POST_ANSWER_REQUEST = "POST_ANSWER_REQUEST";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAILURE = "POST_ANSWER_FAILURE";

export const DELETE_ANSWER_REQUEST = "DELETE_ANSWER_REQUEST";
export const DELETE_ANSWER_SUCCESS = "DELETE_ANSWER_SUCCESS";
export const DELETE_ANSWER_FAILURE = "DELETE_ANSWER_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const VOTE_QUESTION_REQUEST = "VOTE_QUESTION_REQUEST";
export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_QUESTION_FAILURE = "VOTE_QUESTION_FAILURE";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";

export const GET_MY_PLAN_REQUEST = "GET_MY_PLAN_REQUEST";
export const GET_MY_PLAN_SUCCESS = "GET_MY_PLAN_SUCCESS";
export const GET_MY_PLAN_FAILURE = "GET_MY_PLAN_FAILURE";
